"""Добавлен CASCADE в связи board_cards и cards

Revision ID: 06607f760138
Revises: 145d9626b82d
Create Date: 2025-03-15 11:23:22.351320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06607f760138'
down_revision: Union[str, None] = '145d9626b82d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
