"""fix 3

Revision ID: 1ef65d2fb335
Revises: 447cdb830e67
Create Date: 2025-04-20 17:20:36.203227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ef65d2fb335'
down_revision: Union[str, None] = '447cdb830e67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('brackets_session_id_fkey', 'brackets', type_='foreignkey')
    op.create_foreign_key(None, 'brackets', 'sessions', ['session_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'brackets', type_='foreignkey')
    op.create_foreign_key('brackets_session_id_fkey', 'brackets', 'sessions', ['session_id'], ['id'])
    # ### end Alembic commands ###
