"""add is_creator and is_archived to session_participants

Revision ID: 88d1c64add5a
Revises: a3a7612a981a
Create Date: 2025-03-30 17:07:53.354706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88d1c64add5a'
down_revision: Union[str, None] = 'a3a7612a981a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session_participants', sa.Column('is_creator', sa.Boolean(), nullable=True))
    op.add_column('session_participants', sa.Column('is_archived', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session_participants', 'is_archived')
    op.drop_column('session_participants', 'is_creator')
    # ### end Alembic commands ###
