"""fix

Revision ID: c174385907b9
Revises: aff047a58c44
Create Date: 2025-04-20 17:10:15.439300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c174385907b9'
down_revision: Union[str, None] = 'aff047a58c44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('friendships_requester_id_fkey', 'friendships', type_='foreignkey')
    op.drop_constraint('friendships_receiver_id_fkey', 'friendships', type_='foreignkey')
    op.create_foreign_key(None, 'friendships', 'users', ['requester_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'friendships', 'users', ['receiver_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('sessions_board_id_fkey', 'sessions', type_='foreignkey')
    op.create_foreign_key(None, 'sessions', 'boards', ['board_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('swipes_card_id_fkey', 'swipes', type_='foreignkey')
    op.drop_constraint('swipes_session_id_fkey', 'swipes', type_='foreignkey')
    op.create_foreign_key(None, 'swipes', 'cards', ['card_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'swipes', 'sessions', ['session_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'swipes', type_='foreignkey')
    op.drop_constraint(None, 'swipes', type_='foreignkey')
    op.create_foreign_key('swipes_session_id_fkey', 'swipes', 'sessions', ['session_id'], ['id'])
    op.create_foreign_key('swipes_card_id_fkey', 'swipes', 'cards', ['card_id'], ['id'])
    op.drop_constraint(None, 'sessions', type_='foreignkey')
    op.create_foreign_key('sessions_board_id_fkey', 'sessions', 'boards', ['board_id'], ['id'])
    op.drop_constraint(None, 'friendships', type_='foreignkey')
    op.drop_constraint(None, 'friendships', type_='foreignkey')
    op.create_foreign_key('friendships_receiver_id_fkey', 'friendships', 'users', ['receiver_id'], ['id'])
    op.create_foreign_key('friendships_requester_id_fkey', 'friendships', 'users', ['requester_id'], ['id'])
    # ### end Alembic commands ###
